### ISSUE TITLE
unable to hide the player defaults video controller bar

### ISSUE THREAD

**Issue by harshgaba** [PierfrancescoSoffritti/AndroidYouTubePlayer#12]
Hello,
I'm using this player in my sub view but i'm unable to hide the lower controllers bar, is there any way to hide it programmatically, i just want to show the video in specific height and width and not able to make any action taken by user.

**Comment by PierfrancescoSoffritti** [comment]
Hi! I've just implemented the functionality. Starting from version 0.7.7 is possible to hide the UI. Just call hideUI(true) on YouTubePlayerView.

**Comment by harshgaba** [comment]
Hello, Thanks for instant reply, it makes my day, I'm using now version 0.7.7
Thank you very much. Its seriously a very nice youtube player.
