### ISSUE TITLE
No Volume Contol

### ISSUE THREAD

**Issue by harshgaba** [PierfrancescoSoffritti/AndroidYouTubePlayer#13]
Hello,
As i dig into more using AndroidYoutubePlayer, and i really like it, but i'm facing one issue, is there any controls available in player for controlling the volume of video programatically, like setVolume(), etc.

**Comment by PierfrancescoSoffritti** [comment]
No. On Android the volume belongs to the system, not to a single app or view :)

**Comment by harshgaba** [comment]
ok, thanks :)
