### ISSUE TITLE
Video Not playing after proguard

### ISSUE THREAD

**Issue by vipinagrahari** [PierfrancescoSoffritti/AndroidYouTubePlayer#16]
Hi, This is a nice library. I am using this for embedding youtube videos in my android application.
The videos are playing fine when I am using debug apk but when I build a release apk with proguard the videos are not playing. Just the loading icon appears but nothing plays. How to fix this?

**Comment by vipinagrahari** [comment]
Fixed by adding following lines

-keep public class com.pierfrancescosoffritti.youtubeplayer.** {
   public *;
}

-keepnames class com.pierfrancescosoffritti.youtubeplayer.*

**Comment by PierfrancescoSoffritti** [comment]
Right :) I forgot to add info about proguard options in readme. Thank you for reminding me!
