### ISSUE TITLE
Using addview(YouTubePlayerView) and getting error when calling startActivity()

### ISSUE THREAD

**Issue by murmurmuk** [PierfrancescoSoffritti/AndroidYouTubePlayer#28]
I used addview(YouTubePlayerView), and I clicked the icon to load the video in youtube.
The app stopped, and showed error message as below.

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by PierfrancescoSoffritti** [comment]
Hi, I suspect the problem is in your app, not in the library.

**Comment by murmurmuk** [comment]
Sorry, I found my fault.
I initialized YouTubePlayerView with getApplicationContext().
Thanks for your reply.

**Comment by PierfrancescoSoffritti** [comment]
You're welcome!
