### ISSUE TITLE
Video is jittery during playback

### ISSUE THREAD

**Issue by UsamaShafiq91** [PierfrancescoSoffritti/AndroidYouTubePlayer#29]
I create the YouTubePlayer in fragment. During playback the video is jittery. Any help will be appreciated.

**Comment by PierfrancescoSoffritti** [comment]
Hi, what device and version of Android are you using?

**Comment by UsamaShafiq91** [comment]
I am running on Android 6.0.1 and on simulator Android Tv (720p).

**Comment by PierfrancescoSoffritti** [comment]
This YouTube player is running inside of a WebView, therefore it may have bad performance on emulators and low end devices. There's not much to do about it. Have you tried it on a real device?

**Comment by UsamaShafiq91** [comment]
I tried on real device. Issue still exists.

**Comment by PierfrancescoSoffritti** [comment]
The only thing I can suggest is to check if you're using the last version of WebView.
