### ISSUE TITLE
Question: Is the YouTube app required?

### ISSUE THREAD

**Issue by Glurt** [PierfrancescoSoffritti/AndroidYouTubePlayer#3]
I'm assuming that the YouTube app isn't required like it is with the YouTube API but if you could clarify and maybe add it to the readme. You might get a lot of interest from people looking for an alternative that runs on devices without Google apps.

**Comment by PierfrancescoSoffritti** [comment]
Correct, the YouTube app is not required, since this player is basically a WebView.
I'll update update the readme, thank you :)
