### ISSUE TITLE
[Bug]Why FULLSrceen Mod with 2 pause Button

### ISSUE THREAD

**Issue by GoldenCR7** [PierfrancescoSoffritti/AndroidYouTubePlayer#31]
@PierfrancescoSoffritti 
FULLSrceen Mod with 2 pause Button
Please Help!
![_20170601115526](https://cloud.githubusercontent.com/assets/28883779/26664075/8c7cb6d6-46c1-11e7-93b8-46a9fa53e4a7.jpg)

https://goo.gl/photos/6Whn7FP9moKgh7Gc9

**Comment by GoldenCR7** [comment]
![_20170601120605](https://cloud.githubusercontent.com/assets/28883779/26664275/d12b9080-46c2-11e7-815a-832ac5c4f1b1.png)
![_20170601120612](https://cloud.githubusercontent.com/assets/28883779/26664276/d14378b2-46c2-11e7-84a5-acc9de75a663.jpg)
build your sample,android 6.0

**Comment by PierfrancescoSoffritti** [comment]
Hi, remove this line from MainActivity.java

`youTubePlayerView.setCustomActionRight();`

**Comment by GoldenCR7** [comment]
thanks for your help
