### ISSUE TITLE
change autoplay state

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [PierfrancescoSoffritti/AndroidYouTubePlayer#32]
how to change autoplay state ??

**Comment by PierfrancescoSoffritti** [comment]
closed as duplicate of [#30](https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/issues/30)

**Comment by abdulrahmanmajeed** [comment]
would u please comment why u close without any suggestion :(

**Comment by PierfrancescoSoffritti** [comment]
closed as duplicate of [#30](https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/issues/30)
