### ISSUE TITLE
How to change icon youtube when Video goto end

### ISSUE THREAD

**Issue by mdtuyen** [PierfrancescoSoffritti/AndroidYouTubePlayer#35]
When Video goto end, i see a red youtube icon at center of screen. How to remove it ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, this YouTube player is based on the web version of the youtube player, which, by default, shows the red youtube icon. There's no way to remove it.
If you really need to hide it, you could modify the library and overlay a black View to the player, to hide what's underneath.

**Comment by mdtuyen** [comment]
Could you help me use js to remove it from webview ?

**Comment by PierfrancescoSoffritti** [comment]
You could add a black view [here](https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/PlayerControlsWrapper.java) and show it only when the video is loading. Try to replicate the behavior of the progressBar.
