### ISSUE TITLE
Support for playing live stream of youtube

### ISSUE THREAD

**Issue by omi90** [PierfrancescoSoffritti/AndroidYouTubePlayer#39]
Is there a way to play live stream from youtube in youtube player?
As of now there is only way to load normal video which has a video id.
But in my case i have full url of live stream from a channel which does not have a video id.
Example - https://www.youtube.com/embed/live_stream?channel=channel_id

I have checked in official javascript api of youtube also but not able to find anything.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I'm pretty sure you have to use the [YouTube Data API](https://developers.google.com/youtube/v3/docs/) in order to get the ID of the live event.

**Comment by omi90** [comment]
I have tried to use that also but it does not seem to work without oauth (only by api key).
Anyways i have got the workaround solution for now, thanks for help.
