### ISSUE TITLE
Ad Support

### ISSUE THREAD

**Issue by indiandragon** [PierfrancescoSoffritti/AndroidYouTubePlayer#7]
Hi @PierfrancescoSoffritti 

Thanks for your efforts. I'm aware that you are using Youtube's Iframe API as in Youtube's official iOS library. But do you know why the video Ads aren't being displayed in the videos.

Btw, I switched from the official native android API to your library to prevent black screen when it's not able to play Ads. In your library, though still not able to play Ads it's atleast not causing un-handled crashes (or) black screen.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I'm not sure why but the Iframe api is not showing ads. I can't do much about it, it's the Iframe lib's responsibility.
