### ISSUE TITLE
Audio is jittering when hiding/showing the player controls

### ISSUE THREAD

**Issue by Glurt** [PierfrancescoSoffritti/AndroidYouTubePlayer#8]
This doesn't seem to be an issue on my N6 but I've tried it on a VFD 900 and whenever the player controls are animating the audio is really jittery. It's more noticeable in fullscreen and repeatedly tapping on the player seems to highlight the issue.

It also seems to be a problem in Shuffly.

**Comment by PierfrancescoSoffritti** [comment]
Which version of Android are you using? Is it a custom rom?

**Comment by Glurt** [comment]
[Let me know if you need anymore information](http://imgur.com/LFxXtRQ). In the meantime I'll test on some other devices.

**Comment by Glurt** [comment]
S6 Edge: Not present
S7 Edge: Not present
HTC One M8: Not present

Perhaps it's not as big of an issue as I first thought, still, I'd be interested to know why and how many devices are effected.

**Comment by PierfrancescoSoffritti** [comment]
I had the same issue with an old gnexus running Jelly Bean. Think the problem in somewhat relatable to [issue #2](https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/issues/2).
I haven't a lot of experience with WebViews but it looks like a problematic territory D:

**Comment by Glurt** [comment]
The WebView component is actually now separate to the Android os and can be updated independently, like any other app: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

Having just updated it on the VFD 900 the problem has disappeared. Maybe it's worth checking for the version of the WebView and asking the user to update if they're on a problematic version. 

Anyway, this solved my problems I'll go ahead and close this issue.

**Comment by PierfrancescoSoffritti** [comment]
Yeah, I'm aware of the separation of WebView from the OS, but that's not always the problem. In particular for some custom roms I suspect the issue is related to drivers and other low level stuff. But there's not much to do about that D:

I like the idea of checking WebView version at runtime, I'll give it a try :)
