### ISSUE TITLE
Couldn't resolve resource @id/play_button

### ISSUE THREAD

**Issue by Denino** [PierfrancescoSoffritti/AndroidYouTubePlayer#9]
In Android Studio (2.2.2) the layout preview windows keeps showing rendering problems error:

> Couldn't resolve resource @id/play_button

It can be fixed in player_controls.xml layout where custom_action_left_button is refering to play_button (line 160) with minor change of:
`android:layout_toStartOf="@id/play_button"`
to:
`android:layout_toStartOf="@+id/play_button"`

**Comment by PierfrancescoSoffritti** [comment]
Hi, ok! Feel free to send a pull request! 
otherwise I'll fix it my self ASAP :)
